### ISSUE TITLE
Question: How to give all available space to ListBoxItem and its descendants?

### ISSUE THREAD

**Issue by lem0n4de** [AvaloniaCommunity/Avalonia.FuncUI#116]
In the MusicPlayer example, this represents song in the playlist.
```fsharp
let private songTemplate (song: Types.SongRecord) (dispatch: Msg -> unit) =
        StackPanel.create [
            StackPanel.spacing 8.0
            StackPanel.onDoubleTapped ((fun _ -> dispatch (PlaySong song)), SubPatchOptions.OnChangeOf song)
            StackPanel.onKeyUp (fun keyargs ->
                match keyargs.Key with
                | Key.Enter -> dispatch (PlaySong song)
                /// eventually add other shortcuts to re-arrange songs or something alike
                | _ -> ()
            , SubPatchOptions.OnChangeOf song)
            StackPanel.children [
                TextBlock.create [
                    TextBlock.text song.name
                ]
            ]
        ]
```

In the app itself, onDoubleTapped does not fire if the TextBlock does not pressed because StackPanel is the same size as it. I tried to change it by using Grid and DockPanel by they were like that too. I saw this [stackoverflow page](https://stackoverflow.com/questions/838828/how-to-get-a-listbox-itemtemplate-to-stretch-horizontally-the-full-width-of-the) and tried that by adding 
```xaml
<Style Selector="ListBoxItem">
        <Setter Property="HorizontalContentAlignment" Value="Stretch"></Setter>
    </Style>
```
to Styles.xaml but to no avail. Couldn't add it to ListBox because it would throw error saying that property is not available in ListBox.

When i added background property to Grid, like this
```fsharp
Grid.create [
        Grid.rowDefinitions "*"
        Grid.columnDefinitions "*"
        Grid.background Brushes.Aqua
        Grid.children [
```
, it somehow got all available space though. Why is this happening and is there another way to stretch these panels all over ListBoxItem?

**Comment by JaggerJo** [comment]
Hey @lem0n4de !

Thanks for the patience. The StackPanel in the Example actually spans the whole available space. You see this for example when you add a background to it:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/13090415/80794798-1c58e100-8b9b-11ea-8380-194907f2ae4f.png">

And once you've set the Background it actually works. This is because if the background is not set it is ignored during hit testing. You can easily fix this by setting the Background to Transparent. 

```
StackPanel.create [
    StackPanel.background Brushes.Transparent
    ....
]
```

(I'ts a bit strange, but how it's implemented in WPF and Avalonia) 

[WPF transparent background](https://stackoverflow.com/questions/7991314/mouse-event-on-transparent-background)

Let me know if you have further questions 😉

**Comment by lem0n4de** [comment]
Oh, that is strange. But thank you for answering and also for this project (I didn't even realize there was a transparent brush).
