### ISSUE TITLE
Question: How to render inside a modal window?

### ISSUE THREAD

**Issue by B-Reif** [AvaloniaCommunity/Avalonia.FuncUI#138]
I did some poking around and found an example of opening a modal dialog in a separate window in Elmish.WPF using their `Binding` type (https://github.com/elmish/Elmish.WPF/tree/master/src/Samples/NewWindow). Is rendering to a separate dialog box possible in FuncUI? How would I go about doing it?

**Comment by JaggerJo** [comment]
Hi @B-Reif !

thanks for the patience. If you just want to open another window you can do this by dispatching a special message that creates a new window and sets up a subscription.

IIRC @AngelMunoz put together a small app where multiple windows can exchange messages.

Is this what you mean ?

If you actually want to render a modal inside the current window you basically have to do this with views (If there wasn’t something added to avalonia recently).

**Comment by AngelMunoz** [comment]
Yes I think I had one but deleted it since I was not pleased with the design I took for that sample I made this sample that I believe fits better the MVU architecture but lacks inter window communication, for that you might need to use a listener and subscriptions

https://github.com/AngelMunoz/MultiWindow

**But** there's currently an exception being thrown when you try to open the second window as a dialog, 
```
Error: Call from invalid thread
```
@JaggerJo I think this might be a bug unless I'm missing something

**Comment by FoggyFinder** [comment]
> But there's currently an exception being thrown when you try to open the second window as a dialog,

@AngelMunoz I've opened PR with fix: at least it works fine on my system.

**Comment by JaggerJo** [comment]
@AngelMunoz @FoggyFinder thx!

**Comment by AngelMunoz** [comment]
@FoggyFinder thanks!

@B-Reif I just updated that sample to include *A* way to communicate from the dialog to the parent window I don't know if that's the best approach (since I don't handle disposable subs, as well as not sure if there are concurrency issues) but that's what I came up with, also that can be used for multiple windows, not just dialogs say for example you have 10 windows they can all subscribe to the same (or different) event and exchange messages with each other

**Comment by B-Reif** [comment]
Just now catching up with this, thanks for your help! It could be useful to add this example to the FuncUI docs.

Am I right in thinking that you could do the same thing through Elmish with the `Cmd` API? That way you wouldn't have to manage the subscription yourself, at least.

**Comment by rwyrz** [comment]
Uhhh, given that @AngelMunoz seems to have unpublished the repo you mention, can I ask for some example of how to make a modal? My attempts so far had gotten me a deadlock…

**Comment by AngelMunoz** [comment]
I don't know what did I do to that repo, and I can't find it 😶 but I'll be doing a sample later on today just give me some time

**Comment by FoggyFinder** [comment]
> Uhhh, given that @AngelMunoz seems to have unpublished the repo you mention, can I ask for some example of how to make a modal? My attempts so far had gotten me a deadlock…

https://github.com/FoggyFinder/MultiWindow

That's a fork from the sample

**Comment by rwyrz** [comment]
Thanks, I think I get it now. I guess returning a command in addition to the new state allows one to hook some (possibly async) code to be executed alongside the window loop and return a message from that… 

(Just musing out loud for the sake of the next unfortunate soul to wander over here)

**Comment by AngelMunoz** [comment]
@rwyrz I just uploaded the sample, the link above should work now, sorry for the inconvenience

**Comment by AngelMunoz** [comment]
I'll be closing this issue the FoggyFinder Fork shows the sample as well as the other I provided, please feel free to re-open if necessary
