### ISSUE TITLE
Evolving stops when subscription to Button.click event is commented out

### ISSUE THREAD

**Issue by Thecentury** [AvaloniaCommunity/Avalonia.FuncUI#58]
Hi!

When I comment this line out, I get an issue that the whole board stops to evolve:

https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/6cbdad39b1c860edf2c9bb9c0d2fe7c1fd9da312/src/Examples/Examples.GameOfLife/Board.fs#L40

Could you please help me to understand why it happens so?

P.S. Great project, thank you!

**Comment by JaggerJo** [comment]
Hi,

thanks for the issue. It's actually a bug in the example. Because `Array2D` does not implement value equality FuncUI thinks it did not change, so it does not invalidate the view.

It only works because the function you mentioned captures outer scope (the `cellPosition`) and because FuncUI knows that it invalidates the view.

To prevent issues like this (and I will do that with the example now) all types used should implement value equality.

**Comment by JaggerJo** [comment]
https://github.com/AvaloniaCommunity/Avalonia.FuncUI/blob/6cbdad39b1c860edf2c9bb9c0d2fe7c1fd9da312/src/Examples/Examples.GameOfLife/Lib.fs#L5

hmm, just noticed that I'm actually copying.. Will keep you updated.

**Comment by JaggerJo** [comment]
It was actually a bug. (was not able to remove a subscription but replacing worked). This is now fixed.

**Comment by JaggerJo** [comment]
Packages are currently being indexed.
