### ISSUE TITLE
Q: Is Flink Editor source code available?

### ISSUE THREAD

**Issue by KingKnecht** [AvaloniaCommunity/Avalonia.FuncUI#63]
Is the source code of the editor (Flink Editor), shown in the readme, available somewhere?

**Comment by JaggerJo** [comment]
Hi there,

it's a private project I'm working on from time to time. It's not open source, but if you have specific questions I'm happy to answer them.

**Comment by KingKnecht** [comment]
That's a pity ;-) I'm thinking about to write a (another) shape editor/designer. I already wrote different versions in C#/WPF. I just was curious how this could be done in F#. How is data (points, lines, polygons, shapes, etc) organized. Where is the data stored? Is the complete state of the editor passed around when executing functions on shapes? Or are there local mutables holding lists of shapes, so that it is not necessary to  pass around the complete model when manipulating shapes? Does that make any sense?

**Comment by JaggerJo** [comment]
It's a fun little Project :)

> How is data (points, lines, polygons, shapes, etc) organized ?

The Types are separated in different domains and are immutable. 
https://www.youtube.com/watch?v=_Qk7ZcyYZwA

- HistoryDomain (undo/redo functionality)
https://github.com/TheSeamau5/elm-undo-redo

- DocumentDomain (In memory document representation)
Point, PolylineElement, PolygoneElement, Element, Group, Layer, ...

- OverlayDomain (used when drawing -> elements are pushed to the document domain when created)
Point, RectSelection, LassoSelection, Overlay a Document Element

- ToolDomain (Contains an interface all tools implement)
```fsharp
    type ITool =
        abstract PointerMove:   ApplicationDomain.AppState -> Point  -> ApplicationDomain.AppState option
        abstract PointerDown:   ApplicationDomain.AppState -> Point  -> ApplicationDomain.AppState option
        abstract PointerUp:     ApplicationDomain.AppState -> Point  -> ApplicationDomain.AppState option
        abstract TextInput:     ApplicationDomain.AppState -> string -> ApplicationDomain.AppState option
        abstract Cancel:        ApplicationDomain.AppState -> ApplicationDomain.AppState option
        abstract Done:          ApplicationDomain.AppState -> ApplicationDomain.AppState option
        abstract ToolType:      Tool with get
```

- EditorDomain (combines functionality related to editing -> Tools and Overlay)

- ApplicationDomain (root Domain/ where it all comes together)

> Where is the data stored?

The current model is stored using an elm like MVU approach. In my implementation this is called the `Engine` because it also coordinates long running operations and things like this.

> Is the complete state of the editor passed around when executing functions on shapes?

Yes. It's basically a MVU architecture. Messages are passed from the UI or the outer world to the Engine. The engine executes the with the current data model and creates a new one. The views will update and show the new data model.

The only stateful constructs besides the engine are tools. They keep local state (for example start of move, list of licked points, ..).

> Does that make any sense ?
Yes, it does.

**Comment by KingKnecht** [comment]
Cool :-) That gives me a load to reason about. I already read the undo/redo stuff and I have some knowledge about the Elm architecture.

How do you handle "undo-transactions"? E.g. if a shape is moved around. Surely, you don't want to undo every pixel wide movement. So everything happening while a "transaction" is open should be un-done in one undo step. I don't see how a transaction could be established in an functional/immutable way and with the message loop given by the MVU.

If the model iterations are stored in the list of "Past" is that a good idea memory-wise? I know that F# doesn't copy reference types in such scenarios, but I'm unsure if I should be depended on that. I don't like the approach of the command pattern, because in bigger applications that is pretty tedious to implement and for some commands I would have to store the previous state completely anyways.

**Comment by JaggerJo** [comment]
> How do you handle "undo-transactions"? E.g. if a shape is moved around. Surely, you don't want to undo every pixel wide movement. So everything happening while a "transaction" is open should be un-done in one undo step. I don't see how a transaction could be established in an functional/immutable way and with the message loop given by the MVU.

This is also something that I think is complicated. On solution is to introduce intermediate states that are not pushed to the history / are replaced with the next intermediate state or tracked state.
Not sure if this is the best solution bu it should work, let me know if come up with a better solution :)

> If the model iterations are stored in the list of "Past" is that a good idea memory-wise? I know that F# doesn't copy reference types in such scenarios, but I'm unsure if I should be depended on that. I don't like the approach of the command pattern, because in bigger applications that is pretty tedious to implement and for some commands I would have to store the previous state completely anyways.

Haven't noticed memory problems. If your history ends up being to big (and contains things that are no longer reused) you could also limit the undo operations to a specific number.

Also its just so simple. Get your underlaying model of undo right and you don't have to worry about it too much in the future.
