### ISSUE TITLE
Consider grouping the possible UI elements under one module

### ISSUE THREAD

**Issue by Zaid-Ajaj** [AvaloniaCommunity/Avalonia.FuncUI#73]
Hello @JaggerJo, 

This project looks really good and I really like the API used for the view elements. It looks like it was loosely based on [fabulous-simple-elements](https://github.com/Zaid-Ajaj/fabulous-simple-elements). If that the case, I would like to suggest something that I regret not adding to that library -> not being able to see which elements you can use! 

Let me explain: if the user is a beginner, then there is no way to tell which elements are available in the framework. You have to go through the docs and search for elements you need. Of course once you have found them, it becomes easy to find their properties, but only after you have searched the docs. 

I propose to add a module, maybe named `Ava` that contains the constructor for all possible UI elements. Instead of 
```fsharp
Button.create [
    Button.onClick (fun _ -> dispatch Increment)
    Button.content "click to increment"
]
```
I suggest writing:
```fsharp
Ava.button [
    Button.onClick (fun _ -> dispatch Increment)
    Button.content "click to increment"
]
```
This way the beginner user has a nice "entry point" to the possible UI elements that can be used and from there the search for elements becomes even easier. The reason for the name `Ava` is that the formatting works nicely when the propery list is indented with 4 spaces such that the property modules become aligned with the constructor function. This is how it is done in both `Mui` module from Fable.MaterialUI and the `Ant` module from Fable.AntDesign. 

It would be a plus if the property module was also lower-case (but would introduce a breaking change)
```fsharp
Ava.button [
    button.onClick (fun _ -> dispatch Increment)
    button.content "click to increment"
]
``` 
What do you think?

**Comment by AngelMunoz** [comment]
Hello there! I just want to chime in.

I can see why the reason to suggest that, I feel the namespacing on XamarinForms is a little bit weird and you do have to look at the docs to see proper names of elements and such which I believe it's a reason for fabulous-simple-elements to want to group UI elements/controls on a single "entry point"

I don't feel that with Avalonia this is an issue since almost every UI element is namespaced under `Avalonia.Controls` and FuncUI just builds on that; At least I didn't have too much issues discovering the API the first days when experimenting with it.

It might just be familiarity though I see the benefit from people coming from other Elmish based DSL's that the UI elements are usually under one entry point like Html (I think even fsbolero does that as well) or the other examples you mentioned. And for people that are not familiar with Elmish/Avalonia it could be a good way to catch up on the UI Controls


**offtopic**
I like a lot of your projects, I'm a fan of LiteDB.FSharp 💯 

**back on topic**

**Comment by JaggerJo** [comment]
Hey @Zaid-Ajaj,

Thanks, it might be 😉. I've searched and reviewed all elm like DSLs I could find and am really happy how it turned out. 

> This project looks really good and I really like the API used for the view elements. It looks like it was loosely based on fabulous-simple-elements. If that the case, I would like to suggest something that I regret not adding to that library -> not being able to see which elements you can use!
> 
> Let me explain: if the user is a beginner, then there is no way to tell which elements are available in the framework. You have to go through the docs and search for elements you need. Of course once you have found them, it becomes easy to find their properties, but only after you have searched the docs.
> I propose to add a module, maybe named Ava that contains the constructor for all possible UI elements. 

That should already work because all constructors/ and modules of the DSL are located in the `Avalonia.FuncUI.DSL` namespace.

So if you open `Avalonia.FuncUI` you can do this:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/13090415/74102518-5ab6a500-4b44-11ea-9665-9a6747dca0b2.png">

What makes this a bit less useful is that you only can use the constructor, but not the attributes if you haven't opened the namespace that contains the actual control. 

```fsharp
open Avalonia.Controls
open Avalonia.FuncUI

let view =
    DSL.Calendar.create [
        DSL.Calendar. // only shows create because the calendar control lives in `Avalonia.Controls.Calendar`
    ]
```

```fsharp
open Avalonia.Controls
open Avalonia.Controls.Calendar
open Avalonia.FuncUI

let view =
    DSL.Calendar.create [
        DSL.Calendar. // shows all available attributes
    ]
```

So you get a hint that a control exists, but need to open the containing namespace to actually do something useful with it.

> It would be a plus if the property module was also lower-case (but would introduce a breaking change)
> 
> Ava.button [
>     button.onClick (fun _ -> dispatch Increment)
>     button.content "click to increment"
> ]
> What do you think?

It would definitely look nice and clean, but making the module/type lowercase is something I strongly dislike, it makes things harder to understand IMHO.

This currently works:

```fsharp
DSL.Button.create [                          
    Button.dock Dock.Bottom                  
    Button.onClick (fun _ -> dispatch Reset) 
    Button.content "reset"                   
]                                            
```

Do you think using the `DSL` prefix is helpful enough ?

**Comment by JaggerJo** [comment]
@Zaid-Ajaj you still around ? 😊

**Comment by Zaid-Ajaj** [comment]
Hello @JaggerJo, sorry I didn't connect back to you! It seems you have thought about it more than I did :smile: I especially liked this snippet 
```fs
DSL.Button.create [                          
    Button.dock Dock.Bottom                  
    Button.onClick (fun _ -> dispatch Reset) 
    Button.content "reset"                   
]                                            
```
Because there is only one use of `DSL` which becomes the entry point of discovery, really cool stuff.  Thanks for taking the time with your detailed response 💯

**Comment by JaggerJo** [comment]
> Hello @JaggerJo, sorry I didn't connect back to you! It seems you have thought about it more than I did 😄 I especially liked this snippet
> 
> ```fsharp
> DSL.Button.create [                          
>     Button.dock Dock.Bottom                  
>     Button.onClick (fun _ -> dispatch Reset) 
>     Button.content "reset"                   
> ]                                            
> ```
> 
> Because there is only one use of `DSL` which becomes the entry point of discovery, really cool stuff. Thanks for taking the time with your detailed response 💯

@Zaid-Ajaj I have to admit that the formatting was pure luck, I never thought about `DSL.` = `indent size` TBH. But it's neat!

Thanks for the feedback! 😊
