### ISSUE TITLE
Bug - subscription callback doesn't update

### ISSUE THREAD

**Issue by Thecentury** [AvaloniaCommunity/Avalonia.FuncUI#82]
Hi @JaggerJo, please take a look at repro of this bug — https://github.com/Thecentury/Avalonia.FuncUI/commit/07df113485870ea51a7006093040393ddff1d741
Button is expected to increase count by 1 continuously, but works only once.

And in the next commit there is a fix: https://github.com/Thecentury/Avalonia.FuncUI/commit/245d8646a91846215d9dd95a42cb0a339a067d00

Bug happens because in the repro new subscription is equal to the previous one.
I added func into a list of members which are used to compare two subscriptions.
I think another possible fix is to always consider two subscriptions to different if at least one of them captures state.
Cannot estimate which solution is better.

What do you think of it?

**Comment by JaggerJo** [comment]
Hi @Thecentury,

I will take a look. 

Deciding when a subscription needs to be updated is one of the more complicated things FuncUI has to do.

The strategy is to only patch a subscription if on of the following happened:

- Captures outer scope (`FunctionAnalysis.capturesState`)
This is determined using reflection. The result is cached (map<type, bool>) so the performance of it is good.

- Type of the function in the subscription changed.
This is because we can't compare the actual delegates (they are compared by reference). 

Take a look at the `LibTests.fs` File if you haven't already.

If I understand your fix correctly it would patch every subscription on every view change (because the delegate instances are compared by reference). While this would work it would also increase the work the patcher would have to do. I'n a wrong ?

**Comment by Zaid-Ajaj** [comment]
Hello @JaggerJo, for subscriptions please review (Change subscriptions to receive current state of the model)[https://github.com/elmish/elmish/issues/183] because main elmish repo did it handle it properly at all. It is a bit of a long read, but the thread has some good points for subscription implementation

**Comment by Thecentury** [comment]
Hello @JaggerJo, I think it is better to compare subscriptions both by their `capturesState` and consider them different if either of them has it as true.

The problem that my patch fixes is that in the repro subscription is not updated at all because old one and new one are equal.

**Comment by JaggerJo** [comment]
Hey @Zaid-Ajaj,
thanks for the link. FuncUI uses the Elmish implementation, so this should "just work ™️" ?

What I meant with subscription above (and now I see it could be misleading) is basically a subscription to an event (e.g. `Button.onClick`) or a subscription to a property (e.g. `TextBox.onTextChanged`). This attribute type is internally called "Subscription"

```fsharp
// this will result in a `Attr.Subscription` and is internally implemented as an event observable
Button.onClick (fun _ -> dispatch ...)

// this will result in a `Attr.Subscription` and is internally a subscription to an observable property 
TextBlock.OnTextChanged (fun args -> dispatch ...)
```

**Comment by Zaid-Ajaj** [comment]
Oh I see, it is a different story. 

> FuncUI uses the Elmish implementation, so this should "just work ™️" ?

It will work the way Elmish expects it to but that is probably not how people expect it to work (hence the opened issue :wink:)

**Comment by JaggerJo** [comment]
> Hello @JaggerJo, I think it is better to compare subscriptions both by their `capturesState` and consider them different if either of them has it as true.

Exactly! 😉 An this should already work (but seems to have a bug) 

https://github.com/Thecentury/Avalonia.FuncUI/blob/245d8646a91846215d9dd95a42cb0a339a067d00/src/Avalonia.FuncUI/VirtualDom/VirtualDom.Differ.fs#L106

> The problem that my patch fixes is that in the repro subscription is not updated at all because old one and new one are equal.

I need to investigate this. Just overlooked this quick and found this https://github.com/Thecentury/Avalonia.FuncUI/blob/245d8646a91846215d9dd95a42cb0a339a067d00/src/Avalonia.FuncUI/Types.fs#L79 which in my current understanding leads to always unequal.

**Comment by JaggerJo** [comment]
> Oh I see, it is a different story.
> 
> > FuncUI uses the Elmish implementation, so this should "just work ™️" ?
> 
> It will work the way Elmish expects it to but that is probably not how people expect it to work (hence the opened issue 😉)

Ok, I'll take a deeper look 😀

**Comment by Thecentury** [comment]
> Exactly! 😉 An this should already work (but seems to have a bug)

In the repro there is `Grid.children` property (https://github.com/Thecentury/Avalonia.FuncUI/commit/07df113485870ea51a7006093040393ddff1d741#diff-0f818ffcbd99a80ee26fe9bbf63e82d9R27), and after the first update of Button's content the new value of `Grid.children` will become equal to the old one even if subscription captures the state.
And for this very property (`Grid.children`) `ForcePatch` is false.
That is why grid will not get new version of its content and therefore new subscription.
