### ISSUE TITLE
Question: DataGrid? 

### ISSUE THREAD

**Issue by bradphelan** [AvaloniaCommunity/Avalonia.FuncUI#85]
Is there any planned support for DataGrid? I assume it's a heavy beast!!

**Comment by JaggerJo** [comment]
Hey @bradphelan!

The problem with DataGrid is that it's not maintained actively (or at least it wasn't when I checked about a month ago). If I remember correctly the Avalonia Team considered replacing it, because it currently has no maintainer. 

If this changed bindings would be nice! Personally I currently have no plans to add them, but it shouldn't be that complicated (but could be a lot of work) because you can add them gradually.

Let me know if you have further questions :)

**Comment by bradphelan** [comment]
Thanks for the feedback. I guess at the moment I don't really need a datagrid. Sizeable columns would be nice. What I'm really missing is a header row for the ListBox. I notice that there is a HeaderedItemsControl class but the ListBox doesn't implement it. 

At the moment I'm fudging it by putting in a stackpanel at the top and manually padding the margin to make it line up.

![image](https://user-images.githubusercontent.com/17650/76838364-63ca1e80-6834-11ea-9f8c-650f5a31a86e.png)

Any suggestions?

**Comment by JaggerJo** [comment]
Hey @bradphelan,

you should be able to use a `HeaderedItemsControl` (with data or view items) **BUT** you need to provide your own template because the default theme does not include one.

Let me know if you need some help with this.

**Comment by JaggerJo** [comment]
@bradphelan can I close this now ? :)

**Comment by bradphelan** [comment]
Yes
